//------------------------------------------------------------------------------
// <auto-generated>
//     Questo codice è stato generato da uno strumento.
//
//     Le modifiche apportate a questo file possono causare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlloggiatiService
{
    using System.Runtime.Serialization;
    using static AlloggiatiService.ServiceSoapClient;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EsitoOperazione", Namespace="AlloggiatiService")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AlloggiatiService.EsitoOperazioneServizio))]
    public partial class EsitoOperazione : object
    {
        
        private bool esitoField;
        
        private string ErroreCodField;
        
        private string ErroreDesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool esito
        {
            get
            {
                return this.esitoField;
            }
            set
            {
                this.esitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ErroreCod
        {
            get
            {
                return this.ErroreCodField;
            }
            set
            {
                this.ErroreCodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErroreDes
        {
            get
            {
                return this.ErroreDesField;
            }
            set
            {
                this.ErroreDesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EsitoOperazioneServizio", Namespace="AlloggiatiService")]
    public partial class EsitoOperazioneServizio : AlloggiatiService.EsitoOperazione
    {
        
        private string ErroreDettaglioField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ErroreDettaglio
        {
            get
            {
                return this.ErroreDettaglioField;
            }
            set
            {
                this.ErroreDettaglioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenInfo", Namespace="AlloggiatiService")]
    public partial class TokenInfo : object
    {
        
        private System.DateTime issuedField;
        
        private System.DateTime expiresField;
        
        private string tokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime issued
        {
            get
            {
                return this.issuedField;
            }
            set
            {
                this.issuedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime expires
        {
            get
            {
                return this.expiresField;
            }
            set
            {
                this.expiresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="AlloggiatiService", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ElencoSchedineEsito", Namespace="AlloggiatiService")]
    public partial class ElencoSchedineEsito : object
    {
        
        private int SchedineValideField;
        
        private AlloggiatiService.EsitoOperazioneServizio[] DettaglioField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SchedineValide
        {
            get
            {
                return this.SchedineValideField;
            }
            set
            {
                this.SchedineValideField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public AlloggiatiService.EsitoOperazioneServizio[] Dettaglio
        {
            get
            {
                return this.DettaglioField;
            }
            set
            {
                this.DettaglioField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoTabella", Namespace="AlloggiatiService")]
    public enum TipoTabella : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Luoghi = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tipi_Documento = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tipi_Alloggiato = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TipoErrore = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ListaAppartamenti = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="AlloggiatiService", ConfigurationName="AlloggiatiService.ServiceSoap")]
    public interface IServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="AlloggiatiService/GenerateToken", ReplyAction="*")]
        System.Threading.Tasks.Task<AlloggiatiService.GenerateTokenResponse> GenerateTokenAsync(AlloggiatiService.GenerateTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AlloggiatiService/Authentication_Test", ReplyAction="*")]
        System.Threading.Tasks.Task<AlloggiatiService.Authentication_TestResponse> Authentication_TestAsync(AlloggiatiService.Authentication_TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AlloggiatiService/Test", ReplyAction="*")]
        System.Threading.Tasks.Task<AlloggiatiService.TestResponse> TestAsync(AlloggiatiService.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AlloggiatiService/GestioneAppartamenti_Test", ReplyAction="*")]
        System.Threading.Tasks.Task<AlloggiatiService.GestioneAppartamenti_TestResponse> GestioneAppartamenti_TestAsync(AlloggiatiService.GestioneAppartamenti_TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AlloggiatiService/GestioneAppartamenti_FileUnico_Test", ReplyAction="*")]
        System.Threading.Tasks.Task<AlloggiatiService.GestioneAppartamenti_FileUnico_TestResponse> GestioneAppartamenti_FileUnico_TestAsync(AlloggiatiService.GestioneAppartamenti_FileUnico_TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AlloggiatiService/Send", ReplyAction="*")]
        System.Threading.Tasks.Task<AlloggiatiService.SendResponse> SendAsync(AlloggiatiService.SendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AlloggiatiService/GestioneAppartamenti_Send", ReplyAction="*")]
        System.Threading.Tasks.Task<AlloggiatiService.GestioneAppartamenti_SendResponse> GestioneAppartamenti_SendAsync(AlloggiatiService.GestioneAppartamenti_SendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AlloggiatiService/GestioneAppartamenti_FileUnico_Send", ReplyAction="*")]
        System.Threading.Tasks.Task<AlloggiatiService.GestioneAppartamenti_FileUnico_SendResponse> GestioneAppartamenti_FileUnico_SendAsync(AlloggiatiService.GestioneAppartamenti_FileUnico_SendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AlloggiatiService/Tabella", ReplyAction="*")]
        System.Threading.Tasks.Task<AlloggiatiService.TabellaResponse> TabellaAsync(AlloggiatiService.TabellaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AlloggiatiService/Ricevuta", ReplyAction="*")]
        System.Threading.Tasks.Task<AlloggiatiService.RicevutaResponse> RicevutaAsync(AlloggiatiService.RicevutaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AlloggiatiService/GestioneAppartamenti_AggiungiAppartamento", ReplyAction="*")]
        System.Threading.Tasks.Task<AlloggiatiService.GestioneAppartamenti_AggiungiAppartamentoResponse> GestioneAppartamenti_AggiungiAppartamentoAsync(AlloggiatiService.GestioneAppartamenti_AggiungiAppartamentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AlloggiatiService/GestioneAppartamenti_DisabilitaAppartamento", ReplyAction="*")]
        System.Threading.Tasks.Task<AlloggiatiService.GestioneAppartamenti_DisabilitaAppartamentoResponse> GestioneAppartamenti_DisabilitaAppartamentoAsync(AlloggiatiService.GestioneAppartamenti_DisabilitaAppartamentoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateToken", Namespace="AlloggiatiService", Order=0)]
        public AlloggiatiService.GenerateTokenRequestBody Body;
        
        public GenerateTokenRequest()
        {
        }
        
        public GenerateTokenRequest(AlloggiatiService.GenerateTokenRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AlloggiatiService")]
    public partial class GenerateTokenRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Utente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string WsKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public AlloggiatiService.EsitoOperazioneServizio result;
        
        public GenerateTokenRequestBody()
        {
        }
        
        public GenerateTokenRequestBody(string Utente, string Password, string WsKey, AlloggiatiService.EsitoOperazioneServizio result)
        {
            this.Utente = Utente;
            this.Password = Password;
            this.WsKey = WsKey;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateTokenResponse", Namespace="AlloggiatiService", Order=0)]
        public AlloggiatiService.GenerateTokenResponseBody Body;
        
        public GenerateTokenResponse()
        {
        }
        
        public GenerateTokenResponse(AlloggiatiService.GenerateTokenResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AlloggiatiService")]
    public partial class GenerateTokenResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AlloggiatiService.TokenInfo GenerateTokenResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public AlloggiatiService.EsitoOperazioneServizio result;
        
        public GenerateTokenResponseBody()
        {
        }
        
        public GenerateTokenResponseBody(AlloggiatiService.TokenInfo GenerateTokenResult, AlloggiatiService.EsitoOperazioneServizio result)
        {
            this.GenerateTokenResult = GenerateTokenResult;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Authentication_TestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Authentication_Test", Namespace="AlloggiatiService", Order=0)]
        public AlloggiatiService.Authentication_TestRequestBody Body;
        
        public Authentication_TestRequest()
        {
        }
        
        public Authentication_TestRequest(AlloggiatiService.Authentication_TestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AlloggiatiService")]
    public partial class Authentication_TestRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Utente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        public Authentication_TestRequestBody()
        {
        }
        
        public Authentication_TestRequestBody(string Utente, string token)
        {
            this.Utente = Utente;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Authentication_TestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Authentication_TestResponse", Namespace="AlloggiatiService", Order=0)]
        public AlloggiatiService.Authentication_TestResponseBody Body;
        
        public Authentication_TestResponse()
        {
        }
        
        public Authentication_TestResponse(AlloggiatiService.Authentication_TestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AlloggiatiService")]
    public partial class Authentication_TestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AlloggiatiService.EsitoOperazioneServizio Authentication_TestResult;
        
        public Authentication_TestResponseBody()
        {
        }
        
        public Authentication_TestResponseBody(AlloggiatiService.EsitoOperazioneServizio Authentication_TestResult)
        {
            this.Authentication_TestResult = Authentication_TestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Test", Namespace="AlloggiatiService", Order=0)]
        public AlloggiatiService.TestRequestBody Body;
        
        public TestRequest()
        {
        }
        
        public TestRequest(AlloggiatiService.TestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AlloggiatiService")]
    public partial class TestRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Utente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public AlloggiatiService.ArrayOfString ElencoSchedine;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public AlloggiatiService.ElencoSchedineEsito result;
        
        public TestRequestBody()
        {
        }
        
        public TestRequestBody(string Utente, string token, AlloggiatiService.ArrayOfString ElencoSchedine, AlloggiatiService.ElencoSchedineEsito result)
        {
            this.Utente = Utente;
            this.token = token;
            this.ElencoSchedine = ElencoSchedine;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestResponse", Namespace="AlloggiatiService", Order=0)]
        public AlloggiatiService.TestResponseBody Body;
        
        public TestResponse()
        {
        }
        
        public TestResponse(AlloggiatiService.TestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AlloggiatiService")]
    public partial class TestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AlloggiatiService.EsitoOperazioneServizio TestResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public AlloggiatiService.ElencoSchedineEsito result;
        
        public TestResponseBody()
        {
        }
        
        public TestResponseBody(AlloggiatiService.EsitoOperazioneServizio TestResult, AlloggiatiService.ElencoSchedineEsito result)
        {
            this.TestResult = TestResult;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GestioneAppartamenti_TestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GestioneAppartamenti_Test", Namespace="AlloggiatiService", Order=0)]
        public AlloggiatiService.GestioneAppartamenti_TestRequestBody Body;
        
        public GestioneAppartamenti_TestRequest()
        {
        }
        
        public GestioneAppartamenti_TestRequest(AlloggiatiService.GestioneAppartamenti_TestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AlloggiatiService")]
    public partial class GestioneAppartamenti_TestRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Utente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public AlloggiatiService.ArrayOfString ElencoSchedine;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int IdAppartamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public AlloggiatiService.ElencoSchedineEsito result;
        
        public GestioneAppartamenti_TestRequestBody()
        {
        }
        
        public GestioneAppartamenti_TestRequestBody(string Utente, string token, AlloggiatiService.ArrayOfString ElencoSchedine, int IdAppartamento, AlloggiatiService.ElencoSchedineEsito result)
        {
            this.Utente = Utente;
            this.token = token;
            this.ElencoSchedine = ElencoSchedine;
            this.IdAppartamento = IdAppartamento;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GestioneAppartamenti_TestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GestioneAppartamenti_TestResponse", Namespace="AlloggiatiService", Order=0)]
        public AlloggiatiService.GestioneAppartamenti_TestResponseBody Body;
        
        public GestioneAppartamenti_TestResponse()
        {
        }
        
        public GestioneAppartamenti_TestResponse(AlloggiatiService.GestioneAppartamenti_TestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AlloggiatiService")]
    public partial class GestioneAppartamenti_TestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AlloggiatiService.EsitoOperazioneServizio GestioneAppartamenti_TestResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public AlloggiatiService.ElencoSchedineEsito result;
        
        public GestioneAppartamenti_TestResponseBody()
        {
        }
        
        public GestioneAppartamenti_TestResponseBody(AlloggiatiService.EsitoOperazioneServizio GestioneAppartamenti_TestResult, AlloggiatiService.ElencoSchedineEsito result)
        {
            this.GestioneAppartamenti_TestResult = GestioneAppartamenti_TestResult;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GestioneAppartamenti_FileUnico_TestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GestioneAppartamenti_FileUnico_Test", Namespace="AlloggiatiService", Order=0)]
        public AlloggiatiService.GestioneAppartamenti_FileUnico_TestRequestBody Body;
        
        public GestioneAppartamenti_FileUnico_TestRequest()
        {
        }
        
        public GestioneAppartamenti_FileUnico_TestRequest(AlloggiatiService.GestioneAppartamenti_FileUnico_TestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AlloggiatiService")]
    public partial class GestioneAppartamenti_FileUnico_TestRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Utente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public AlloggiatiService.ArrayOfString ElencoSchedine;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public AlloggiatiService.ElencoSchedineEsito result;
        
        public GestioneAppartamenti_FileUnico_TestRequestBody()
        {
        }
        
        public GestioneAppartamenti_FileUnico_TestRequestBody(string Utente, string token, AlloggiatiService.ArrayOfString ElencoSchedine, AlloggiatiService.ElencoSchedineEsito result)
        {
            this.Utente = Utente;
            this.token = token;
            this.ElencoSchedine = ElencoSchedine;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GestioneAppartamenti_FileUnico_TestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GestioneAppartamenti_FileUnico_TestResponse", Namespace="AlloggiatiService", Order=0)]
        public AlloggiatiService.GestioneAppartamenti_FileUnico_TestResponseBody Body;
        
        public GestioneAppartamenti_FileUnico_TestResponse()
        {
        }
        
        public GestioneAppartamenti_FileUnico_TestResponse(AlloggiatiService.GestioneAppartamenti_FileUnico_TestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AlloggiatiService")]
    public partial class GestioneAppartamenti_FileUnico_TestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AlloggiatiService.EsitoOperazioneServizio GestioneAppartamenti_FileUnico_TestResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public AlloggiatiService.ElencoSchedineEsito result;
        
        public GestioneAppartamenti_FileUnico_TestResponseBody()
        {
        }
        
        public GestioneAppartamenti_FileUnico_TestResponseBody(AlloggiatiService.EsitoOperazioneServizio GestioneAppartamenti_FileUnico_TestResult, AlloggiatiService.ElencoSchedineEsito result)
        {
            this.GestioneAppartamenti_FileUnico_TestResult = GestioneAppartamenti_FileUnico_TestResult;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send", Namespace="AlloggiatiService", Order=0)]
        public AlloggiatiService.SendRequestBody Body;
        
        public SendRequest()
        {
        }
        
        public SendRequest(AlloggiatiService.SendRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AlloggiatiService")]
    public partial class SendRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Utente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public AlloggiatiService.ArrayOfString ElencoSchedine;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public AlloggiatiService.ElencoSchedineEsito result;
        
        public SendRequestBody()
        {
        }
        
        public SendRequestBody(string Utente, string token, AlloggiatiService.ArrayOfString ElencoSchedine, AlloggiatiService.ElencoSchedineEsito result)
        {
            this.Utente = Utente;
            this.token = token;
            this.ElencoSchedine = ElencoSchedine;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendResponse", Namespace="AlloggiatiService", Order=0)]
        public AlloggiatiService.SendResponseBody Body;
        
        public SendResponse()
        {
        }
        
        public SendResponse(AlloggiatiService.SendResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AlloggiatiService")]
    public partial class SendResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AlloggiatiService.EsitoOperazioneServizio SendResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public AlloggiatiService.ElencoSchedineEsito result;
        
        public SendResponseBody()
        {
        }
        
        public SendResponseBody(AlloggiatiService.EsitoOperazioneServizio SendResult, AlloggiatiService.ElencoSchedineEsito result)
        {
            this.SendResult = SendResult;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GestioneAppartamenti_SendRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GestioneAppartamenti_Send", Namespace="AlloggiatiService", Order=0)]
        public AlloggiatiService.GestioneAppartamenti_SendRequestBody Body;
        
        public GestioneAppartamenti_SendRequest()
        {
        }
        
        public GestioneAppartamenti_SendRequest(AlloggiatiService.GestioneAppartamenti_SendRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AlloggiatiService")]
    public partial class GestioneAppartamenti_SendRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Utente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public AlloggiatiService.ArrayOfString ElencoSchedine;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int IdAppartamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public AlloggiatiService.ElencoSchedineEsito result;
        
        public GestioneAppartamenti_SendRequestBody()
        {
        }
        
        public GestioneAppartamenti_SendRequestBody(string Utente, string token, AlloggiatiService.ArrayOfString ElencoSchedine, int IdAppartamento, AlloggiatiService.ElencoSchedineEsito result)
        {
            this.Utente = Utente;
            this.token = token;
            this.ElencoSchedine = ElencoSchedine;
            this.IdAppartamento = IdAppartamento;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GestioneAppartamenti_SendResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GestioneAppartamenti_SendResponse", Namespace="AlloggiatiService", Order=0)]
        public AlloggiatiService.GestioneAppartamenti_SendResponseBody Body;
        
        public GestioneAppartamenti_SendResponse()
        {
        }
        
        public GestioneAppartamenti_SendResponse(AlloggiatiService.GestioneAppartamenti_SendResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AlloggiatiService")]
    public partial class GestioneAppartamenti_SendResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AlloggiatiService.EsitoOperazioneServizio GestioneAppartamenti_SendResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public AlloggiatiService.ElencoSchedineEsito result;
        
        public GestioneAppartamenti_SendResponseBody()
        {
        }
        
        public GestioneAppartamenti_SendResponseBody(AlloggiatiService.EsitoOperazioneServizio GestioneAppartamenti_SendResult, AlloggiatiService.ElencoSchedineEsito result)
        {
            this.GestioneAppartamenti_SendResult = GestioneAppartamenti_SendResult;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GestioneAppartamenti_FileUnico_SendRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GestioneAppartamenti_FileUnico_Send", Namespace="AlloggiatiService", Order=0)]
        public AlloggiatiService.GestioneAppartamenti_FileUnico_SendRequestBody Body;
        
        public GestioneAppartamenti_FileUnico_SendRequest()
        {
        }
        
        public GestioneAppartamenti_FileUnico_SendRequest(AlloggiatiService.GestioneAppartamenti_FileUnico_SendRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AlloggiatiService")]
    public partial class GestioneAppartamenti_FileUnico_SendRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Utente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public AlloggiatiService.ArrayOfString ElencoSchedine;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public AlloggiatiService.ElencoSchedineEsito result;
        
        public GestioneAppartamenti_FileUnico_SendRequestBody()
        {
        }
        
        public GestioneAppartamenti_FileUnico_SendRequestBody(string Utente, string token, AlloggiatiService.ArrayOfString ElencoSchedine, AlloggiatiService.ElencoSchedineEsito result)
        {
            this.Utente = Utente;
            this.token = token;
            this.ElencoSchedine = ElencoSchedine;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GestioneAppartamenti_FileUnico_SendResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GestioneAppartamenti_FileUnico_SendResponse", Namespace="AlloggiatiService", Order=0)]
        public AlloggiatiService.GestioneAppartamenti_FileUnico_SendResponseBody Body;
        
        public GestioneAppartamenti_FileUnico_SendResponse()
        {
        }
        
        public GestioneAppartamenti_FileUnico_SendResponse(AlloggiatiService.GestioneAppartamenti_FileUnico_SendResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AlloggiatiService")]
    public partial class GestioneAppartamenti_FileUnico_SendResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AlloggiatiService.EsitoOperazioneServizio GestioneAppartamenti_FileUnico_SendResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public AlloggiatiService.ElencoSchedineEsito result;
        
        public GestioneAppartamenti_FileUnico_SendResponseBody()
        {
        }
        
        public GestioneAppartamenti_FileUnico_SendResponseBody(AlloggiatiService.EsitoOperazioneServizio GestioneAppartamenti_FileUnico_SendResult, AlloggiatiService.ElencoSchedineEsito result)
        {
            this.GestioneAppartamenti_FileUnico_SendResult = GestioneAppartamenti_FileUnico_SendResult;
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TabellaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Tabella", Namespace="AlloggiatiService", Order=0)]
        public AlloggiatiService.TabellaRequestBody Body;
        
        public TabellaRequest()
        {
        }
        
        public TabellaRequest(AlloggiatiService.TabellaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AlloggiatiService")]
    public partial class TabellaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Utente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public AlloggiatiService.TipoTabella tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CSV;
        
        public TabellaRequestBody()
        {
        }
        
        public TabellaRequestBody(string Utente, string token, AlloggiatiService.TipoTabella tipo, string CSV)
        {
            this.Utente = Utente;
            this.token = token;
            this.tipo = tipo;
            this.CSV = CSV;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TabellaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TabellaResponse", Namespace="AlloggiatiService", Order=0)]
        public AlloggiatiService.TabellaResponseBody Body;
        
        public TabellaResponse()
        {
        }
        
        public TabellaResponse(AlloggiatiService.TabellaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AlloggiatiService")]
    public partial class TabellaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AlloggiatiService.EsitoOperazioneServizio TabellaResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CSV;
        
        public TabellaResponseBody()
        {
        }
        
        public TabellaResponseBody(AlloggiatiService.EsitoOperazioneServizio TabellaResult, string CSV)
        {
            this.TabellaResult = TabellaResult;
            this.CSV = CSV;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RicevutaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ricevuta", Namespace="AlloggiatiService", Order=0)]
        public AlloggiatiService.RicevutaRequestBody Body;
        
        public RicevutaRequest()
        {
        }
        
        public RicevutaRequest(AlloggiatiService.RicevutaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AlloggiatiService")]
    public partial class RicevutaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Utente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime Data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] PDF;
        
        public RicevutaRequestBody()
        {
        }
        
        public RicevutaRequestBody(string Utente, string token, System.DateTime Data, byte[] PDF)
        {
            this.Utente = Utente;
            this.token = token;
            this.Data = Data;
            this.PDF = PDF;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RicevutaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RicevutaResponse", Namespace="AlloggiatiService", Order=0)]
        public AlloggiatiService.RicevutaResponseBody Body;
        
        public RicevutaResponse()
        {
        }
        
        public RicevutaResponse(AlloggiatiService.RicevutaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AlloggiatiService")]
    public partial class RicevutaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AlloggiatiService.EsitoOperazioneServizio RicevutaResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] PDF;
        
        public RicevutaResponseBody()
        {
        }
        
        public RicevutaResponseBody(AlloggiatiService.EsitoOperazioneServizio RicevutaResult, byte[] PDF)
        {
            this.RicevutaResult = RicevutaResult;
            this.PDF = PDF;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GestioneAppartamenti_AggiungiAppartamentoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GestioneAppartamenti_AggiungiAppartamento", Namespace="AlloggiatiService", Order=0)]
        public AlloggiatiService.GestioneAppartamenti_AggiungiAppartamentoRequestBody Body;
        
        public GestioneAppartamenti_AggiungiAppartamentoRequest()
        {
        }
        
        public GestioneAppartamenti_AggiungiAppartamentoRequest(AlloggiatiService.GestioneAppartamenti_AggiungiAppartamentoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AlloggiatiService")]
    public partial class GestioneAppartamenti_AggiungiAppartamentoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Utente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descrizione;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ComuneCodice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Indirizzo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Proprietario;
        
        public GestioneAppartamenti_AggiungiAppartamentoRequestBody()
        {
        }
        
        public GestioneAppartamenti_AggiungiAppartamentoRequestBody(string Utente, string token, string Descrizione, string ComuneCodice, string Indirizzo, string Proprietario)
        {
            this.Utente = Utente;
            this.token = token;
            this.Descrizione = Descrizione;
            this.ComuneCodice = ComuneCodice;
            this.Indirizzo = Indirizzo;
            this.Proprietario = Proprietario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GestioneAppartamenti_AggiungiAppartamentoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GestioneAppartamenti_AggiungiAppartamentoResponse", Namespace="AlloggiatiService", Order=0)]
        public AlloggiatiService.GestioneAppartamenti_AggiungiAppartamentoResponseBody Body;
        
        public GestioneAppartamenti_AggiungiAppartamentoResponse()
        {
        }
        
        public GestioneAppartamenti_AggiungiAppartamentoResponse(AlloggiatiService.GestioneAppartamenti_AggiungiAppartamentoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AlloggiatiService")]
    public partial class GestioneAppartamenti_AggiungiAppartamentoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AlloggiatiService.EsitoOperazioneServizio GestioneAppartamenti_AggiungiAppartamentoResult;
        
        public GestioneAppartamenti_AggiungiAppartamentoResponseBody()
        {
        }
        
        public GestioneAppartamenti_AggiungiAppartamentoResponseBody(AlloggiatiService.EsitoOperazioneServizio GestioneAppartamenti_AggiungiAppartamentoResult)
        {
            this.GestioneAppartamenti_AggiungiAppartamentoResult = GestioneAppartamenti_AggiungiAppartamentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GestioneAppartamenti_DisabilitaAppartamentoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GestioneAppartamenti_DisabilitaAppartamento", Namespace="AlloggiatiService", Order=0)]
        public AlloggiatiService.GestioneAppartamenti_DisabilitaAppartamentoRequestBody Body;
        
        public GestioneAppartamenti_DisabilitaAppartamentoRequest()
        {
        }
        
        public GestioneAppartamenti_DisabilitaAppartamentoRequest(AlloggiatiService.GestioneAppartamenti_DisabilitaAppartamentoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AlloggiatiService")]
    public partial class GestioneAppartamenti_DisabilitaAppartamentoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Utente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int IdAppartamento;
        
        public GestioneAppartamenti_DisabilitaAppartamentoRequestBody()
        {
        }
        
        public GestioneAppartamenti_DisabilitaAppartamentoRequestBody(string Utente, string token, int IdAppartamento)
        {
            this.Utente = Utente;
            this.token = token;
            this.IdAppartamento = IdAppartamento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GestioneAppartamenti_DisabilitaAppartamentoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GestioneAppartamenti_DisabilitaAppartamentoResponse", Namespace="AlloggiatiService", Order=0)]
        public AlloggiatiService.GestioneAppartamenti_DisabilitaAppartamentoResponseBody Body;
        
        public GestioneAppartamenti_DisabilitaAppartamentoResponse()
        {
        }
        
        public GestioneAppartamenti_DisabilitaAppartamentoResponse(AlloggiatiService.GestioneAppartamenti_DisabilitaAppartamentoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AlloggiatiService")]
    public partial class GestioneAppartamenti_DisabilitaAppartamentoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AlloggiatiService.EsitoOperazioneServizio GestioneAppartamenti_DisabilitaAppartamentoResult;
        
        public GestioneAppartamenti_DisabilitaAppartamentoResponseBody()
        {
        }
        
        public GestioneAppartamenti_DisabilitaAppartamentoResponseBody(AlloggiatiService.EsitoOperazioneServizio GestioneAppartamenti_DisabilitaAppartamentoResult)
        {
            this.GestioneAppartamenti_DisabilitaAppartamentoResult = GestioneAppartamenti_DisabilitaAppartamentoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IServiceSoapChannel : AlloggiatiService.IServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<AlloggiatiService.IServiceSoap>, AlloggiatiService.IServiceSoap
    {
        
        /// <summary>
        /// Implementare questo metodo parziale per configurare l'endpoint servizio.
        /// </summary>
        /// <param name="serviceEndpoint">Endpoint da configurare</param>
        /// <param name="clientCredentials">Credenziali del client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public ServiceSoapClient(IEndpointConfigurationProvider endpointConfigurationProvider, IRemoteAddressProvider remoteAddressProvider) :
            this(endpointConfigurationProvider.EndpointConfiguration, remoteAddressProvider.RemoteAddress)
        { }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AlloggiatiService.GenerateTokenResponse> GenerateTokenAsync(AlloggiatiService.GenerateTokenRequest request)
        {
            return base.Channel.GenerateTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<AlloggiatiService.Authentication_TestResponse> Authentication_TestAsync(AlloggiatiService.Authentication_TestRequest request)
        {
            return base.Channel.Authentication_TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<AlloggiatiService.TestResponse> TestAsync(AlloggiatiService.TestRequest request)
        {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<AlloggiatiService.GestioneAppartamenti_TestResponse> GestioneAppartamenti_TestAsync(AlloggiatiService.GestioneAppartamenti_TestRequest request)
        {
            return base.Channel.GestioneAppartamenti_TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<AlloggiatiService.GestioneAppartamenti_FileUnico_TestResponse> GestioneAppartamenti_FileUnico_TestAsync(AlloggiatiService.GestioneAppartamenti_FileUnico_TestRequest request)
        {
            return base.Channel.GestioneAppartamenti_FileUnico_TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<AlloggiatiService.SendResponse> SendAsync(AlloggiatiService.SendRequest request)
        {
            return base.Channel.SendAsync(request);
        }
        
        public System.Threading.Tasks.Task<AlloggiatiService.GestioneAppartamenti_SendResponse> GestioneAppartamenti_SendAsync(AlloggiatiService.GestioneAppartamenti_SendRequest request)
        {
            return base.Channel.GestioneAppartamenti_SendAsync(request);
        }
        
        public System.Threading.Tasks.Task<AlloggiatiService.GestioneAppartamenti_FileUnico_SendResponse> GestioneAppartamenti_FileUnico_SendAsync(AlloggiatiService.GestioneAppartamenti_FileUnico_SendRequest request)
        {
            return base.Channel.GestioneAppartamenti_FileUnico_SendAsync(request);
        }
        
        public System.Threading.Tasks.Task<AlloggiatiService.TabellaResponse> TabellaAsync(AlloggiatiService.TabellaRequest request)
        {
            return base.Channel.TabellaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AlloggiatiService.RicevutaResponse> RicevutaAsync(AlloggiatiService.RicevutaRequest request)
        {
            return base.Channel.RicevutaAsync(request);
        }
        
        public System.Threading.Tasks.Task<AlloggiatiService.GestioneAppartamenti_AggiungiAppartamentoResponse> GestioneAppartamenti_AggiungiAppartamentoAsync(AlloggiatiService.GestioneAppartamenti_AggiungiAppartamentoRequest request)
        {
            return base.Channel.GestioneAppartamenti_AggiungiAppartamentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AlloggiatiService.GestioneAppartamenti_DisabilitaAppartamentoResponse> GestioneAppartamenti_DisabilitaAppartamentoAsync(AlloggiatiService.GestioneAppartamenti_DisabilitaAppartamentoRequest request)
        {
            return base.Channel.GestioneAppartamenti_DisabilitaAppartamentoAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://alloggiatiweb.poliziadistato.it/service/service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://alloggiatiweb.poliziadistato.it/service/service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceSoap,
            
            ServiceSoap12,
        }
    }

    public interface IEndpointConfigurationProvider
    {
        public EndpointConfiguration EndpointConfiguration { get; }
    }

    public class EndpointConfigurationProvider : IEndpointConfigurationProvider
    {
        public EndpointConfiguration EndpointConfiguration => EndpointConfiguration.ServiceSoap12;
    }

    public interface IRemoteAddressProvider
    {
        public string RemoteAddress { get; }
    }

    public class RemoteAddressProvider : IRemoteAddressProvider
    {
        public string RemoteAddress => "https://alloggiatiweb.poliziadistato.it/service";
    }
}
