//------------------------------------------------------------------------------
// <auto-generated>
//     Questo codice è stato generato da uno strumento.
//
//     Le modifiche apportate a questo file possono causare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C59Service
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", ConfigurationName="C59Service.EC59ServiceEndpoint")]
    public interface EC59ServiceEndpoint
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(commonPO))]
        System.Threading.Tasks.Task<C59Service.inviaC59FullResponse> inviaC59FullAsync(C59Service.inviaC59Full request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(commonPO))]
        System.Threading.Tasks.Task<C59Service.ultimoC59Response> ultimoC59Async(C59Service.ultimoC59 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(commonPO))]
        System.Threading.Tasks.Task<C59Service.listaStruttureResponse> listaStruttureAsync(C59Service.listaStrutture request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(commonPO))]
        System.Threading.Tasks.Task<C59Service.inviaC59Response> inviaC59Async(C59Service.inviaC59 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/")]
    public partial class c59WSPO
    {
        
        private System.DateTime dataMovimentazioneField;
        
        private bool dataMovimentazioneFieldSpecified;
        
        private bool esercizioApertoField;
        
        private movimentoWSPO[] movimentiField;
        
        private long totaleArriviField;
        
        private long totalePartenzeField;
        
        private long totalePresentiField;
        
        private long unitaAbitativeDisponibiliField;
        
        private long unitaAbitativeOccupateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime dataMovimentazione
        {
            get
            {
                return this.dataMovimentazioneField;
            }
            set
            {
                this.dataMovimentazioneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataMovimentazioneSpecified
        {
            get
            {
                return this.dataMovimentazioneFieldSpecified;
            }
            set
            {
                this.dataMovimentazioneFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool esercizioAperto
        {
            get
            {
                return this.esercizioApertoField;
            }
            set
            {
                this.esercizioApertoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("movimenti", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public movimentoWSPO[] movimenti
        {
            get
            {
                return this.movimentiField;
            }
            set
            {
                this.movimentiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long totaleArrivi
        {
            get
            {
                return this.totaleArriviField;
            }
            set
            {
                this.totaleArriviField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long totalePartenze
        {
            get
            {
                return this.totalePartenzeField;
            }
            set
            {
                this.totalePartenzeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long totalePresenti
        {
            get
            {
                return this.totalePresentiField;
            }
            set
            {
                this.totalePresentiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long unitaAbitativeDisponibili
        {
            get
            {
                return this.unitaAbitativeDisponibiliField;
            }
            set
            {
                this.unitaAbitativeDisponibiliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public long unitaAbitativeOccupate
        {
            get
            {
                return this.unitaAbitativeOccupateField;
            }
            set
            {
                this.unitaAbitativeOccupateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/")]
    public partial class movimentoWSPO
    {
        
        private long arriviField;
        
        private bool italiaField;
        
        private long partenzeField;
        
        private string targaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long arrivi
        {
            get
            {
                return this.arriviField;
            }
            set
            {
                this.arriviField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool italia
        {
            get
            {
                return this.italiaField;
            }
            set
            {
                this.italiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long partenze
        {
            get
            {
                return this.partenzeField;
            }
            set
            {
                this.partenzeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string targa
        {
            get
            {
                return this.targaField;
            }
            set
            {
                this.targaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/")]
    public partial class struttura
    {
        
        private string nameField;
        
        private long struttura1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("struttura", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long struttura1
        {
            get
            {
                return this.struttura1Field;
            }
            set
            {
                this.struttura1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(dettaglioMovimentiC59PO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(c59PO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/")]
    public abstract partial class commonPO
    {
        
        private long idObjField;
        
        private bool idObjFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long idObj
        {
            get
            {
                return this.idObjField;
            }
            set
            {
                this.idObjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idObjSpecified
        {
            get
            {
                return this.idObjFieldSpecified;
            }
            set
            {
                this.idObjFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/")]
    public partial class dettaglioMovimentiC59PO : commonPO
    {
        
        private long arriviField;
        
        private bool arriviFieldSpecified;
        
        private System.DateTime dataMovimentazioneField;
        
        private bool dataMovimentazioneFieldSpecified;
        
        private long idNazioneField;
        
        private bool idNazioneFieldSpecified;
        
        private long idProvinciaField;
        
        private bool idProvinciaFieldSpecified;
        
        private bool isItaliaField;
        
        private bool isItaliaFieldSpecified;
        
        private long numeroAlloggiField;
        
        private bool numeroAlloggiFieldSpecified;
        
        private long partenzeField;
        
        private bool partenzeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long arrivi
        {
            get
            {
                return this.arriviField;
            }
            set
            {
                this.arriviField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arriviSpecified
        {
            get
            {
                return this.arriviFieldSpecified;
            }
            set
            {
                this.arriviFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime dataMovimentazione
        {
            get
            {
                return this.dataMovimentazioneField;
            }
            set
            {
                this.dataMovimentazioneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataMovimentazioneSpecified
        {
            get
            {
                return this.dataMovimentazioneFieldSpecified;
            }
            set
            {
                this.dataMovimentazioneFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long idNazione
        {
            get
            {
                return this.idNazioneField;
            }
            set
            {
                this.idNazioneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idNazioneSpecified
        {
            get
            {
                return this.idNazioneFieldSpecified;
            }
            set
            {
                this.idNazioneFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long idProvincia
        {
            get
            {
                return this.idProvinciaField;
            }
            set
            {
                this.idProvinciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProvinciaSpecified
        {
            get
            {
                return this.idProvinciaFieldSpecified;
            }
            set
            {
                this.idProvinciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool isItalia
        {
            get
            {
                return this.isItaliaField;
            }
            set
            {
                this.isItaliaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isItaliaSpecified
        {
            get
            {
                return this.isItaliaFieldSpecified;
            }
            set
            {
                this.isItaliaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long numeroAlloggi
        {
            get
            {
                return this.numeroAlloggiField;
            }
            set
            {
                this.numeroAlloggiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroAlloggiSpecified
        {
            get
            {
                return this.numeroAlloggiFieldSpecified;
            }
            set
            {
                this.numeroAlloggiFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long partenze
        {
            get
            {
                return this.partenzeField;
            }
            set
            {
                this.partenzeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool partenzeSpecified
        {
            get
            {
                return this.partenzeFieldSpecified;
            }
            set
            {
                this.partenzeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/")]
    public partial class c59PO : commonPO
    {
        
        private System.DateTime dataMovimentazioneField;
        
        private bool dataMovimentazioneFieldSpecified;
        
        private bool isEsercizioApertoField;
        
        private bool isEsercizioApertoFieldSpecified;
        
        private bool isValidatoField;
        
        private bool isValidatoFieldSpecified;
        
        private dettaglioMovimentiC59PO[] listaDettaglioMovimentiField;
        
        private long totaleArriviField;
        
        private bool totaleArriviFieldSpecified;
        
        private long totalePartenzeField;
        
        private bool totalePartenzeFieldSpecified;
        
        private long totalePresentiField;
        
        private bool totalePresentiFieldSpecified;
        
        private long unitaAbitativeDisponibiliField;
        
        private bool unitaAbitativeDisponibiliFieldSpecified;
        
        private long unitaAbitativeOccupateField;
        
        private bool unitaAbitativeOccupateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime dataMovimentazione
        {
            get
            {
                return this.dataMovimentazioneField;
            }
            set
            {
                this.dataMovimentazioneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataMovimentazioneSpecified
        {
            get
            {
                return this.dataMovimentazioneFieldSpecified;
            }
            set
            {
                this.dataMovimentazioneFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool isEsercizioAperto
        {
            get
            {
                return this.isEsercizioApertoField;
            }
            set
            {
                this.isEsercizioApertoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isEsercizioApertoSpecified
        {
            get
            {
                return this.isEsercizioApertoFieldSpecified;
            }
            set
            {
                this.isEsercizioApertoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool isValidato
        {
            get
            {
                return this.isValidatoField;
            }
            set
            {
                this.isValidatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isValidatoSpecified
        {
            get
            {
                return this.isValidatoFieldSpecified;
            }
            set
            {
                this.isValidatoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaDettaglioMovimenti", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public dettaglioMovimentiC59PO[] listaDettaglioMovimenti
        {
            get
            {
                return this.listaDettaglioMovimentiField;
            }
            set
            {
                this.listaDettaglioMovimentiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long totaleArrivi
        {
            get
            {
                return this.totaleArriviField;
            }
            set
            {
                this.totaleArriviField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totaleArriviSpecified
        {
            get
            {
                return this.totaleArriviFieldSpecified;
            }
            set
            {
                this.totaleArriviFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long totalePartenze
        {
            get
            {
                return this.totalePartenzeField;
            }
            set
            {
                this.totalePartenzeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalePartenzeSpecified
        {
            get
            {
                return this.totalePartenzeFieldSpecified;
            }
            set
            {
                this.totalePartenzeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long totalePresenti
        {
            get
            {
                return this.totalePresentiField;
            }
            set
            {
                this.totalePresentiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalePresentiSpecified
        {
            get
            {
                return this.totalePresentiFieldSpecified;
            }
            set
            {
                this.totalePresentiFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public long unitaAbitativeDisponibili
        {
            get
            {
                return this.unitaAbitativeDisponibiliField;
            }
            set
            {
                this.unitaAbitativeDisponibiliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unitaAbitativeDisponibiliSpecified
        {
            get
            {
                return this.unitaAbitativeDisponibiliFieldSpecified;
            }
            set
            {
                this.unitaAbitativeDisponibiliFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public long unitaAbitativeOccupate
        {
            get
            {
                return this.unitaAbitativeOccupateField;
            }
            set
            {
                this.unitaAbitativeOccupateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unitaAbitativeOccupateSpecified
        {
            get
            {
                return this.unitaAbitativeOccupateFieldSpecified;
            }
            set
            {
                this.unitaAbitativeOccupateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/")]
    public partial class movimentiC59
    {
        
        private c59PO[] elencoC59Field;
        
        private long strutturaField;
        
        private bool strutturaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("elencoC59", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public c59PO[] elencoC59
        {
            get
            {
                return this.elencoC59Field;
            }
            set
            {
                this.elencoC59Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long struttura
        {
            get
            {
                return this.strutturaField;
            }
            set
            {
                this.strutturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool strutturaSpecified
        {
            get
            {
                return this.strutturaFieldSpecified;
            }
            set
            {
                this.strutturaFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="inviaC59Full", WrapperNamespace="http://movimentazione.manager.web.module.dtu.infotn.it/", IsWrapped=true)]
    public partial class inviaC59Full
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long struttura;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public C59Service.c59WSPO c59;
        
        public inviaC59Full()
        {
        }
        
        public inviaC59Full(string username, string password, long struttura, C59Service.c59WSPO c59)
        {
            this.username = username;
            this.password = password;
            this.struttura = struttura;
            this.c59 = c59;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="inviaC59FullResponse", WrapperNamespace="http://movimentazione.manager.web.module.dtu.infotn.it/", IsWrapped=true)]
    public partial class inviaC59FullResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public C59Service.c59WSPO[] @return;
        
        public inviaC59FullResponse()
        {
        }
        
        public inviaC59FullResponse(C59Service.c59WSPO[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ultimoC59", WrapperNamespace="http://movimentazione.manager.web.module.dtu.infotn.it/", IsWrapped=true)]
    public partial class ultimoC59
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long struttura;
        
        public ultimoC59()
        {
        }
        
        public ultimoC59(string username, string password, long struttura)
        {
            this.username = username;
            this.password = password;
            this.struttura = struttura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ultimoC59Response", WrapperNamespace="http://movimentazione.manager.web.module.dtu.infotn.it/", IsWrapped=true)]
    public partial class ultimoC59Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public C59Service.movimentiC59 @return;
        
        public ultimoC59Response()
        {
        }
        
        public ultimoC59Response(C59Service.movimentiC59 @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaStrutture", WrapperNamespace="http://movimentazione.manager.web.module.dtu.infotn.it/", IsWrapped=true)]
    public partial class listaStrutture
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public listaStrutture()
        {
        }
        
        public listaStrutture(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaStruttureResponse", WrapperNamespace="http://movimentazione.manager.web.module.dtu.infotn.it/", IsWrapped=true)]
    public partial class listaStruttureResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public C59Service.struttura[] @return;
        
        public listaStruttureResponse()
        {
        }
        
        public listaStruttureResponse(C59Service.struttura[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="inviaC59", WrapperNamespace="http://movimentazione.manager.web.module.dtu.infotn.it/", IsWrapped=true)]
    public partial class inviaC59
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long struttura;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dataMovimentazione;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long unitaAbitativeOccupate;
        
        public inviaC59()
        {
        }
        
        public inviaC59(string username, string password, long struttura, System.DateTime dataMovimentazione, long unitaAbitativeOccupate)
        {
            this.username = username;
            this.password = password;
            this.struttura = struttura;
            this.dataMovimentazione = dataMovimentazione;
            this.unitaAbitativeOccupate = unitaAbitativeOccupate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="inviaC59Response", WrapperNamespace="http://movimentazione.manager.web.module.dtu.infotn.it/", IsWrapped=true)]
    public partial class inviaC59Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public C59Service.movimentiC59 @return;
        
        public inviaC59Response()
        {
        }
        
        public inviaC59Response(C59Service.movimentiC59 @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface EC59ServiceEndpointChannel : C59Service.EC59ServiceEndpoint, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class EC59ServiceEndpointClient : System.ServiceModel.ClientBase<C59Service.EC59ServiceEndpoint>, C59Service.EC59ServiceEndpoint
    {
        
        /// <summary>
        /// Implementare questo metodo parziale per configurare l'endpoint servizio.
        /// </summary>
        /// <param name="serviceEndpoint">Endpoint da configurare</param>
        /// <param name="clientCredentials">Credenziali del client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EC59ServiceEndpointClient() : 
                base(EC59ServiceEndpointClient.GetDefaultBinding(), EC59ServiceEndpointClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.EC59ServiceEndpointPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EC59ServiceEndpointClient(EndpointConfiguration endpointConfiguration) : 
                base(EC59ServiceEndpointClient.GetBindingForEndpoint(endpointConfiguration), EC59ServiceEndpointClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EC59ServiceEndpointClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EC59ServiceEndpointClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EC59ServiceEndpointClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EC59ServiceEndpointClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EC59ServiceEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<C59Service.inviaC59FullResponse> inviaC59FullAsync(C59Service.inviaC59Full request)
        {
            return base.Channel.inviaC59FullAsync(request);
        }
        
        public System.Threading.Tasks.Task<C59Service.ultimoC59Response> ultimoC59Async(C59Service.ultimoC59 request)
        {
            return base.Channel.ultimoC59Async(request);
        }
        
        public System.Threading.Tasks.Task<C59Service.listaStruttureResponse> listaStruttureAsync(C59Service.listaStrutture request)
        {
            return base.Channel.listaStruttureAsync(request);
        }
        
        public System.Threading.Tasks.Task<C59Service.inviaC59Response> inviaC59Async(C59Service.inviaC59 request)
        {
            return base.Channel.inviaC59Async(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EC59ServiceEndpointPort))
            {
                System.ServiceModel.BasicHttpsBinding result = new System.ServiceModel.BasicHttpsBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EC59ServiceEndpointPort))
            {
                return new System.ServiceModel.EndpointAddress("https://dtu.provincia.tn.it/c59service");
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EC59ServiceEndpointClient.GetBindingForEndpoint(EndpointConfiguration.EC59ServiceEndpointPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EC59ServiceEndpointClient.GetEndpointAddress(EndpointConfiguration.EC59ServiceEndpointPort);
        }
        
        public enum EndpointConfiguration
        {
            
            EC59ServiceEndpointPort,
        }
    }
}
