// <auto-generated />
using System;
using BookingCalendarApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingCalendarApi.Repository.NETCore.Migrations
{
    [DbContext(typeof(BookingCalendarContext))]
    [Migration("20230801200229_AdjustNationDescriptionsForISTAT")]
    partial class AdjustNationDescriptionsForISTAT
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BookingCalendarApi.Models.Entities.ColorAssignment", b =>
                {
                    b.Property<string>("BookingId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("BookingId");

                    b.ToTable("ColorAssignments");
                });

            modelBuilder.Entity("BookingCalendarApi.Models.Entities.Floor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("BookingCalendarApi.Models.Entities.Nation", b =>
                {
                    b.Property<string>("Iso")
                        .HasColumnType("varchar(255)");

                    b.Property<ulong>("Code")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Iso");

                    b.ToTable("Nations");

                    b.HasData(
                        new
                        {
                            Iso = "AD",
                            Code = 100000202ul,
                            Description = "ALTRI PAESI EUROPEI"
                        },
                        new
                        {
                            Iso = "AE",
                            Code = 100000322ul,
                            Description = "ALTRI PAESI ASIA OCCIDENTALE"
                        },
                        new
                        {
                            Iso = "AF",
                            Code = 100000301ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "AG",
                            Code = 100000503ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "AI",
                            Code = 100000402ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "AL",
                            Code = 100000201ul,
                            Description = "ALBANIA"
                        },
                        new
                        {
                            Iso = "AM",
                            Code = 100000358ul,
                            Description = "ALTRI PAESI ASIA OCCIDENTALE"
                        },
                        new
                        {
                            Iso = "AO",
                            Code = 100000402ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "AQ",
                            Code = 100000733ul,
                            Description = "ALTRI PAESI EXTRAEUROPEI"
                        },
                        new
                        {
                            Iso = "AR",
                            Code = 100000602ul,
                            Description = "ARGENTINA"
                        },
                        new
                        {
                            Iso = "AS",
                            Code = 100000798ul,
                            Description = "ALTRI PAESI O TERRITORI OCEANIA"
                        },
                        new
                        {
                            Iso = "AT",
                            Code = 100000203ul,
                            Description = "AUSTRIA"
                        },
                        new
                        {
                            Iso = "AU",
                            Code = 100000701ul,
                            Description = "AUSTRALIA"
                        },
                        new
                        {
                            Iso = "AW",
                            Code = 100000358ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "AX",
                            Code = 100000223ul,
                            Description = "FINLANDIA"
                        },
                        new
                        {
                            Iso = "AZ",
                            Code = 100000359ul,
                            Description = "ALTRI PAESI ASIA OCCIDENTALE"
                        },
                        new
                        {
                            Iso = "BA",
                            Code = 100000252ul,
                            Description = "ALTRI PAESI EUROPEI"
                        },
                        new
                        {
                            Iso = "BB",
                            Code = 100000506ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "BD",
                            Code = 100000305ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "BE",
                            Code = 100000206ul,
                            Description = "BELGIO"
                        },
                        new
                        {
                            Iso = "BF",
                            Code = 100000409ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "BG",
                            Code = 100000209ul,
                            Description = "BULGARIA"
                        },
                        new
                        {
                            Iso = "BH",
                            Code = 100000304ul,
                            Description = "ALTRI PAESI ASIA OCCIDENTALE"
                        },
                        new
                        {
                            Iso = "BI",
                            Code = 100000410ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "BJ",
                            Code = 100000406ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "BL",
                            Code = 100000797ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "BM",
                            Code = 100000406ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "BN",
                            Code = 100000309ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "BO",
                            Code = 100000604ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "BQ",
                            Code = 100000232ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "BR",
                            Code = 100000605ul,
                            Description = "BRASILE"
                        },
                        new
                        {
                            Iso = "BS",
                            Code = 100000505ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "BT",
                            Code = 100000306ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "BV",
                            Code = 100000223ul,
                            Description = "ALTRI PAESI EXTRAEUROPEI"
                        },
                        new
                        {
                            Iso = "BW",
                            Code = 100000408ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "BY",
                            Code = 100000256ul,
                            Description = "RUSSIA"
                        },
                        new
                        {
                            Iso = "BZ",
                            Code = 100000507ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "CA",
                            Code = 100000509ul,
                            Description = "CANADA"
                        },
                        new
                        {
                            Iso = "CC",
                            Code = 100000223ul,
                            Description = "AUSTRALIA"
                        },
                        new
                        {
                            Iso = "CD",
                            Code = 100000998ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "CF",
                            Code = 100000257ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "CG",
                            Code = 100000257ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "CH",
                            Code = 100000241ul,
                            Description = "SVIZZERA"
                        },
                        new
                        {
                            Iso = "CI",
                            Code = 100000404ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "CK",
                            Code = 100000223ul,
                            Description = "ALTRI PAESI O TERRITORI OCEANIA"
                        },
                        new
                        {
                            Iso = "CL",
                            Code = 100000606ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "CM",
                            Code = 100000411ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "CN",
                            Code = 100000606ul,
                            Description = "CINA"
                        },
                        new
                        {
                            Iso = "CO",
                            Code = 100000608ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "CR",
                            Code = 100000404ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "CU",
                            Code = 100000514ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "CV",
                            Code = 100000413ul,
                            Description = "ALTRI PAESI AFRICA MEDITERRANEA"
                        },
                        new
                        {
                            Iso = "CW",
                            Code = 100000514ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "CX",
                            Code = 100000223ul,
                            Description = "AUSTRALIA"
                        },
                        new
                        {
                            Iso = "CY",
                            Code = 100000315ul,
                            Description = "CIPRO"
                        },
                        new
                        {
                            Iso = "CZ",
                            Code = 100000257ul,
                            Description = "REPUBBLICA CECA"
                        },
                        new
                        {
                            Iso = "DE",
                            Code = 100000216ul,
                            Description = "GERMANIA - REP"
                        },
                        new
                        {
                            Iso = "DJ",
                            Code = 100000424ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "DK",
                            Code = 100000212ul,
                            Description = "DANIMARCA"
                        },
                        new
                        {
                            Iso = "DM",
                            Code = 100000515ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "DO",
                            Code = 100000997ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "DZ",
                            Code = 100000401ul,
                            Description = "ALTRI PAESI AFRICA MEDITERRANEA"
                        },
                        new
                        {
                            Iso = "EC",
                            Code = 100000609ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "EE",
                            Code = 100000247ul,
                            Description = "ESTONIA"
                        },
                        new
                        {
                            Iso = "EG",
                            Code = 100000419ul,
                            Description = "EGITTO"
                        },
                        new
                        {
                            Iso = "EH",
                            Code = 100000533ul,
                            Description = "ALTRI PAESI AFRICA MEDITERRANEA"
                        },
                        new
                        {
                            Iso = "ER",
                            Code = 100000466ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "ES",
                            Code = 100000239ul,
                            Description = "SPAGNA"
                        },
                        new
                        {
                            Iso = "ET",
                            Code = 100000420ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "FI",
                            Code = 100000214ul,
                            Description = "FINLANDIA"
                        },
                        new
                        {
                            Iso = "FJ",
                            Code = 100000703ul,
                            Description = "ALTRI PAESI O TERRITORI OCEANIA"
                        },
                        new
                        {
                            Iso = "FK",
                            Code = 100000223ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "FM",
                            Code = 100000311ul,
                            Description = "ALTRI PAESI O TERRITORI OCEANIA"
                        },
                        new
                        {
                            Iso = "FO",
                            Code = 100000755ul,
                            Description = "ALTRI PAESI EUROPEI"
                        },
                        new
                        {
                            Iso = "FR",
                            Code = 100000215ul,
                            Description = "FRANCIA"
                        },
                        new
                        {
                            Iso = "GA",
                            Code = 100000421ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "GB",
                            Code = 100000219ul,
                            Description = "REGNO UNITO"
                        },
                        new
                        {
                            Iso = "GD",
                            Code = 100000519ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "GE",
                            Code = 100000360ul,
                            Description = "ALTRI PAESI ASIA OCCIDENTALE"
                        },
                        new
                        {
                            Iso = "GF",
                            Code = 100000612ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "GG",
                            Code = 100000761ul,
                            Description = "REGNO UNITO"
                        },
                        new
                        {
                            Iso = "GH",
                            Code = 100000423ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "GI",
                            Code = 100000326ul,
                            Description = "REGNO UNITO"
                        },
                        new
                        {
                            Iso = "GL",
                            Code = 100000758ul,
                            Description = "DANIMARCA"
                        },
                        new
                        {
                            Iso = "GM",
                            Code = 100000422ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "GN",
                            Code = 100000425ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "GP",
                            Code = 100000759ul,
                            Description = "FRANCIA"
                        },
                        new
                        {
                            Iso = "GQ",
                            Code = 100000427ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "GR",
                            Code = 100000220ul,
                            Description = "GRECIA"
                        },
                        new
                        {
                            Iso = "GS",
                            Code = 100000360ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "GT",
                            Code = 100000523ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "GU",
                            Code = 100000760ul,
                            Description = "ALTRI PAESI O TERRITORI OCEANIA"
                        },
                        new
                        {
                            Iso = "GW",
                            Code = 100000427ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "GY",
                            Code = 100000612ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "HK",
                            Code = 110000005ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "HM",
                            Code = 100000223ul,
                            Description = "AUSTRALIA"
                        },
                        new
                        {
                            Iso = "HN",
                            Code = 100000525ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "HR",
                            Code = 100000250ul,
                            Description = "CROAZIA"
                        },
                        new
                        {
                            Iso = "HT",
                            Code = 100000524ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "HU",
                            Code = 100000244ul,
                            Description = "UNGHERIA"
                        },
                        new
                        {
                            Iso = "ID",
                            Code = 100000331ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "IE",
                            Code = 100000221ul,
                            Description = "IRLANDA"
                        },
                        new
                        {
                            Iso = "IL",
                            Code = 100000334ul,
                            Description = "ISRAELE"
                        },
                        new
                        {
                            Iso = "IM",
                            Code = 100000223ul,
                            Description = "REGNO UNITO"
                        },
                        new
                        {
                            Iso = "IN",
                            Code = 100000330ul,
                            Description = "INDIA"
                        },
                        new
                        {
                            Iso = "IO",
                            Code = 100000457ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "IQ",
                            Code = 100000333ul,
                            Description = "ALTRI PAESI ASIA OCCIDENTALE"
                        },
                        new
                        {
                            Iso = "IR",
                            Code = 100000332ul,
                            Description = "ALTRI PAESI ASIA OCCIDENTALE"
                        },
                        new
                        {
                            Iso = "IS",
                            Code = 100000223ul,
                            Description = "ISLANDA"
                        },
                        new
                        {
                            Iso = "IT",
                            Code = 100000100ul,
                            Description = "ITALIA"
                        },
                        new
                        {
                            Iso = "JE",
                            Code = 100000223ul,
                            Description = "REGNO UNITO"
                        },
                        new
                        {
                            Iso = "JM",
                            Code = 100000518ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "JO",
                            Code = 100000327ul,
                            Description = "ALTRI PAESI ASIA OCCIDENTALE"
                        },
                        new
                        {
                            Iso = "JP",
                            Code = 100000326ul,
                            Description = "GIAPPONE"
                        },
                        new
                        {
                            Iso = "KE",
                            Code = 100000428ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "KG",
                            Code = 100000361ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "KH",
                            Code = 100000310ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "KI",
                            Code = 100000708ul,
                            Description = "ALTRI PAESI O TERRITORI OCEANIA"
                        },
                        new
                        {
                            Iso = "KM",
                            Code = 100000417ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "KN",
                            Code = 100000795ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "KP",
                            Code = 100000319ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "KR",
                            Code = 100000320ul,
                            Description = "COREA DEL SUD"
                        },
                        new
                        {
                            Iso = "KW",
                            Code = 100000335ul,
                            Description = "ALTRI PAESI ASIA OCCIDENTALE"
                        },
                        new
                        {
                            Iso = "KY",
                            Code = 100000223ul,
                            Description = "ALTRI PAESI EXTRAEUROPEI"
                        },
                        new
                        {
                            Iso = "KZ",
                            Code = 100000356ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "LA",
                            Code = 100000336ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "LB",
                            Code = 100000337ul,
                            Description = "ALTRI PAESI ASIA OCCIDENTALE"
                        },
                        new
                        {
                            Iso = "LC",
                            Code = 100000532ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "LI",
                            Code = 100000225ul,
                            Description = "ALTRI PAESI EUROPEI"
                        },
                        new
                        {
                            Iso = "LK",
                            Code = 100000239ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "LR",
                            Code = 100000430ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "LS",
                            Code = 100000429ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "LT",
                            Code = 100000249ul,
                            Description = "LITUANIA"
                        },
                        new
                        {
                            Iso = "LU",
                            Code = 100000226ul,
                            Description = "LUSSEMBURGO"
                        },
                        new
                        {
                            Iso = "LV",
                            Code = 100000248ul,
                            Description = "LETTONIA"
                        },
                        new
                        {
                            Iso = "LY",
                            Code = 100000431ul,
                            Description = "ALTRI PAESI AFRICA MEDITERRANEA"
                        },
                        new
                        {
                            Iso = "MA",
                            Code = 100000436ul,
                            Description = "ALTRI PAESI AFRICA MEDITERRANEA"
                        },
                        new
                        {
                            Iso = "MC",
                            Code = 100000234ul,
                            Description = "ALTRI PAESI EUROPEI"
                        },
                        new
                        {
                            Iso = "MD",
                            Code = 100000254ul,
                            Description = "ALTRI PAESI EUROPEI"
                        },
                        new
                        {
                            Iso = "ME",
                            Code = 100001001ul,
                            Description = "ALTRI PAESI EUROPEI"
                        },
                        new
                        {
                            Iso = "MF",
                            Code = 100000797ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "MG",
                            Code = 100000432ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "MH",
                            Code = 100000223ul,
                            Description = "ALTRI PAESI O TERRITORI OCEANIA"
                        },
                        new
                        {
                            Iso = "MK",
                            Code = 100000253ul,
                            Description = "ALTRI PAESI EUROPEI"
                        },
                        new
                        {
                            Iso = "ML",
                            Code = 100000435ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "MM",
                            Code = 100000256ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "MN",
                            Code = 100000341ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "MO",
                            Code = 110000003ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "MP",
                            Code = 100000223ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "MQ",
                            Code = 100000773ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "MR",
                            Code = 100000437ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "MS",
                            Code = 100000777ul,
                            Description = "ALTRI PAESI EXTRAEUROPEI"
                        },
                        new
                        {
                            Iso = "MT",
                            Code = 100000227ul,
                            Description = "MALTA"
                        },
                        new
                        {
                            Iso = "MU",
                            Code = 100000437ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "MV",
                            Code = 100000339ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "MW",
                            Code = 100000434ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "MX",
                            Code = 100000527ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "MY",
                            Code = 100000767ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "MZ",
                            Code = 100000440ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "NA",
                            Code = 100000441ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "NC",
                            Code = 100000780ul,
                            Description = "ALTRI PAESI O TERRITORI OCEANIA"
                        },
                        new
                        {
                            Iso = "NE",
                            Code = 100000442ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "NF",
                            Code = 100000223ul,
                            Description = "AUSTRALIA"
                        },
                        new
                        {
                            Iso = "NG",
                            Code = 100000443ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "NI",
                            Code = 100000529ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "NL",
                            Code = 100000232ul,
                            Description = "PAESI BASSI"
                        },
                        new
                        {
                            Iso = "NO",
                            Code = 100000231ul,
                            Description = "NORVEGIA"
                        },
                        new
                        {
                            Iso = "NP",
                            Code = 100000342ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "NR",
                            Code = 100000715ul,
                            Description = "ALTRI PAESI O TERRITORI OCEANIA"
                        },
                        new
                        {
                            Iso = "NU",
                            Code = 100000443ul,
                            Description = "ALTRI PAESI O TERRITORI OCEANIA"
                        },
                        new
                        {
                            Iso = "NZ",
                            Code = 100000719ul,
                            Description = "NUOVA ZELANDA"
                        },
                        new
                        {
                            Iso = "OM",
                            Code = 100000343ul,
                            Description = "ALTRI PAESI ASIA OCCIDENTALE"
                        },
                        new
                        {
                            Iso = "PA",
                            Code = 100000530ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "PE",
                            Code = 100000615ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA'"
                        },
                        new
                        {
                            Iso = "PF",
                            Code = 100000787ul,
                            Description = "ALTRI PAESI O TERRITORI OCEANIA"
                        },
                        new
                        {
                            Iso = "PG",
                            Code = 100000530ul,
                            Description = "ALTRI PAESI O TERRITORI OCEANIA"
                        },
                        new
                        {
                            Iso = "PH",
                            Code = 100000323ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "PK",
                            Code = 100000344ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "PL",
                            Code = 100000233ul,
                            Description = "POLONIA"
                        },
                        new
                        {
                            Iso = "PM",
                            Code = 100000797ul,
                            Description = "FRANCIA"
                        },
                        new
                        {
                            Iso = "PN",
                            Code = 100000223ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "PR",
                            Code = 100000233ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "PS",
                            Code = 100000536ul,
                            Description = "ALTRI PAESI ASIA OCCIDENTALE"
                        },
                        new
                        {
                            Iso = "PT",
                            Code = 100000234ul,
                            Description = "PORTOGALLO"
                        },
                        new
                        {
                            Iso = "PW",
                            Code = 100000344ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "PY",
                            Code = 100000614ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "QA",
                            Code = 100000345ul,
                            Description = "ALTRI PAESI ASIA OCCIDENTALE"
                        },
                        new
                        {
                            Iso = "RE",
                            Code = 100000765ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "RO",
                            Code = 100000235ul,
                            Description = "ROMANIA"
                        },
                        new
                        {
                            Iso = "RS",
                            Code = 100001000ul,
                            Description = "ALTRI PAESI EUROPEI"
                        },
                        new
                        {
                            Iso = "RU",
                            Code = 100000245ul,
                            Description = "RUSSIA"
                        },
                        new
                        {
                            Iso = "RW",
                            Code = 100000446ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "SA",
                            Code = 100000302ul,
                            Description = "ALTRI PAESI ASIA OCCIDENTALE"
                        },
                        new
                        {
                            Iso = "SB",
                            Code = 100000223ul,
                            Description = "ALTRI PAESI O TERRITORI OCEANIA"
                        },
                        new
                        {
                            Iso = "SC",
                            Code = 100001000ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "SD",
                            Code = 100000455ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "SE",
                            Code = 100000240ul,
                            Description = "SVEZIA"
                        },
                        new
                        {
                            Iso = "SG",
                            Code = 100000346ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "SH",
                            Code = 100000799ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "SI",
                            Code = 100000251ul,
                            Description = "SLOVENIA"
                        },
                        new
                        {
                            Iso = "SJ",
                            Code = 100000616ul,
                            Description = "NORVEGIA"
                        },
                        new
                        {
                            Iso = "SK",
                            Code = 100000348ul,
                            Description = "SLOVACCHIA"
                        },
                        new
                        {
                            Iso = "SL",
                            Code = 100000451ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "SM",
                            Code = 100000236ul,
                            Description = "ALTRI PAESI EUROPEI"
                        },
                        new
                        {
                            Iso = "SN",
                            Code = 100000450ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "SO",
                            Code = 100000453ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "SR",
                            Code = 100000616ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "SS",
                            Code = 100000455ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "ST",
                            Code = 100000448ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "SV",
                            Code = 100000517ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "SX",
                            Code = 100000346ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "SY",
                            Code = 100000348ul,
                            Description = "ALTRI PAESI ASIA OCCIDENTALE"
                        },
                        new
                        {
                            Iso = "SZ",
                            Code = 100000456ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "TC",
                            Code = 100000223ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "TD",
                            Code = 100000415ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "TF",
                            Code = 100000457ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "TG",
                            Code = 100000458ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "TH",
                            Code = 100000349ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "TJ",
                            Code = 100000362ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "TK",
                            Code = 100000806ul,
                            Description = "ALTRI PAESI O TERRITORI OCEANIA"
                        },
                        new
                        {
                            Iso = "TL",
                            Code = 100000805ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "TM",
                            Code = 100000364ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "TN",
                            Code = 100000460ul,
                            Description = "ALTRI PAESI AFRICA MEDITERRANEA"
                        },
                        new
                        {
                            Iso = "TO",
                            Code = 100000730ul,
                            Description = "ALTRI PAESI O TERRITORI OCEANIA"
                        },
                        new
                        {
                            Iso = "TR",
                            Code = 100000351ul,
                            Description = "TURCHIA"
                        },
                        new
                        {
                            Iso = "TT",
                            Code = 100000617ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "TV",
                            Code = 100000731ul,
                            Description = "ALTRI PAESI O TERRITORI OCEANIA"
                        },
                        new
                        {
                            Iso = "TW",
                            Code = 100000998ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "TZ",
                            Code = 100000457ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "UA",
                            Code = 100000243ul,
                            Description = "UCRAINA"
                        },
                        new
                        {
                            Iso = "UG",
                            Code = 100000461ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "UK",
                            Code = 100000219ul,
                            Description = "REGNO UNITO"
                        },
                        new
                        {
                            Iso = "UM",
                            Code = 100000223ul,
                            Description = "U.S.A."
                        },
                        new
                        {
                            Iso = "US",
                            Code = 100000536ul,
                            Description = "U.S.A."
                        },
                        new
                        {
                            Iso = "UY",
                            Code = 100000618ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "UZ",
                            Code = 100000357ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "VA",
                            Code = 100000246ul,
                            Description = "ITALIA"
                        },
                        new
                        {
                            Iso = "VC",
                            Code = 100000797ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "VE",
                            Code = 100000619ul,
                            Description = "VENEZUELA"
                        },
                        new
                        {
                            Iso = "VG",
                            Code = 100000764ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "VI",
                            Code = 100000764ul,
                            Description = "ALTRI PAESI CENTRO - SUD AMERICA"
                        },
                        new
                        {
                            Iso = "VN",
                            Code = 100000353ul,
                            Description = "ALTRI PAESI DELL'ASIA"
                        },
                        new
                        {
                            Iso = "VU",
                            Code = 100000732ul,
                            Description = "ALTRI PAESI O TERRITORI OCEANIA"
                        },
                        new
                        {
                            Iso = "WF",
                            Code = 100000815ul,
                            Description = "ALTRI PAESI O TERRITORI OCEANIA"
                        },
                        new
                        {
                            Iso = "WS",
                            Code = 100000727ul,
                            Description = "ALTRI PAESI O TERRITORI OCEANIA"
                        },
                        new
                        {
                            Iso = "YE",
                            Code = 100000354ul,
                            Description = "ALTRI PAESI ASIA OCCIDENTALE"
                        },
                        new
                        {
                            Iso = "YT",
                            Code = 100000774ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "ZA",
                            Code = 100000467ul,
                            Description = "SUD AFRICA"
                        },
                        new
                        {
                            Iso = "ZM",
                            Code = 100000464ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        },
                        new
                        {
                            Iso = "ZW",
                            Code = 100000465ul,
                            Description = "ALTRI PAESI DELL'AFRICA"
                        });
                });

            modelBuilder.Entity("BookingCalendarApi.Models.Entities.Room", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("FloorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("BookingCalendarApi.Models.Entities.RoomAssignment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomAssignments");
                });

            modelBuilder.Entity("BookingCalendarApi.Models.Entities.SessionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("BookingCalendarApi.Models.Entities.Room", b =>
                {
                    b.HasOne("BookingCalendarApi.Models.Entities.Floor", null)
                        .WithMany("Rooms")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookingCalendarApi.Models.Entities.RoomAssignment", b =>
                {
                    b.HasOne("BookingCalendarApi.Models.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookingCalendarApi.Models.Entities.Floor", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
