//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingCalendarApi.NETFramework.C59Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", ConfigurationName="C59Service.EC59ServiceEndpoint")]
    public interface EC59ServiceEndpoint {
        
        // CODEGEN: Il parametro 'return' richiede informazioni sullo schema aggiuntive che non possono essere acquisite utilizzando la modalità parametro. L'attributo specifico è 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(commonPO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BookingCalendarApi.NETFramework.C59Service.inviaC59FullResponse inviaC59Full(BookingCalendarApi.NETFramework.C59Service.inviaC59Full request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BookingCalendarApi.NETFramework.C59Service.inviaC59FullResponse> inviaC59FullAsync(BookingCalendarApi.NETFramework.C59Service.inviaC59Full request);
        
        // CODEGEN: Il parametro 'return' richiede informazioni sullo schema aggiuntive che non possono essere acquisite utilizzando la modalità parametro. L'attributo specifico è 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(commonPO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BookingCalendarApi.NETFramework.C59Service.ultimoC59Response ultimoC59(BookingCalendarApi.NETFramework.C59Service.ultimoC59 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BookingCalendarApi.NETFramework.C59Service.ultimoC59Response> ultimoC59Async(BookingCalendarApi.NETFramework.C59Service.ultimoC59 request);
        
        // CODEGEN: Il parametro 'return' richiede informazioni sullo schema aggiuntive che non possono essere acquisite utilizzando la modalità parametro. L'attributo specifico è 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(commonPO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BookingCalendarApi.NETFramework.C59Service.listaStruttureResponse listaStrutture(BookingCalendarApi.NETFramework.C59Service.listaStrutture request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BookingCalendarApi.NETFramework.C59Service.listaStruttureResponse> listaStruttureAsync(BookingCalendarApi.NETFramework.C59Service.listaStrutture request);
        
        // CODEGEN: Il parametro 'return' richiede informazioni sullo schema aggiuntive che non possono essere acquisite utilizzando la modalità parametro. L'attributo specifico è 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(commonPO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BookingCalendarApi.NETFramework.C59Service.inviaC59Response inviaC59(BookingCalendarApi.NETFramework.C59Service.inviaC59 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<BookingCalendarApi.NETFramework.C59Service.inviaC59Response> inviaC59Async(BookingCalendarApi.NETFramework.C59Service.inviaC59 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/")]
    public partial class c59WSPO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime dataMovimentazioneField;
        
        private bool dataMovimentazioneFieldSpecified;
        
        private bool esercizioApertoField;
        
        private movimentoWSPO[] movimentiField;
        
        private long totaleArriviField;
        
        private long totalePartenzeField;
        
        private long totalePresentiField;
        
        private long unitaAbitativeDisponibiliField;
        
        private long unitaAbitativeOccupateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime dataMovimentazione {
            get {
                return this.dataMovimentazioneField;
            }
            set {
                this.dataMovimentazioneField = value;
                this.RaisePropertyChanged("dataMovimentazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataMovimentazioneSpecified {
            get {
                return this.dataMovimentazioneFieldSpecified;
            }
            set {
                this.dataMovimentazioneFieldSpecified = value;
                this.RaisePropertyChanged("dataMovimentazioneSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool esercizioAperto {
            get {
                return this.esercizioApertoField;
            }
            set {
                this.esercizioApertoField = value;
                this.RaisePropertyChanged("esercizioAperto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("movimenti", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public movimentoWSPO[] movimenti {
            get {
                return this.movimentiField;
            }
            set {
                this.movimentiField = value;
                this.RaisePropertyChanged("movimenti");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long totaleArrivi {
            get {
                return this.totaleArriviField;
            }
            set {
                this.totaleArriviField = value;
                this.RaisePropertyChanged("totaleArrivi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long totalePartenze {
            get {
                return this.totalePartenzeField;
            }
            set {
                this.totalePartenzeField = value;
                this.RaisePropertyChanged("totalePartenze");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long totalePresenti {
            get {
                return this.totalePresentiField;
            }
            set {
                this.totalePresentiField = value;
                this.RaisePropertyChanged("totalePresenti");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long unitaAbitativeDisponibili {
            get {
                return this.unitaAbitativeDisponibiliField;
            }
            set {
                this.unitaAbitativeDisponibiliField = value;
                this.RaisePropertyChanged("unitaAbitativeDisponibili");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public long unitaAbitativeOccupate {
            get {
                return this.unitaAbitativeOccupateField;
            }
            set {
                this.unitaAbitativeOccupateField = value;
                this.RaisePropertyChanged("unitaAbitativeOccupate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/")]
    public partial class movimentoWSPO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long arriviField;
        
        private bool italiaField;
        
        private long partenzeField;
        
        private string targaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long arrivi {
            get {
                return this.arriviField;
            }
            set {
                this.arriviField = value;
                this.RaisePropertyChanged("arrivi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool italia {
            get {
                return this.italiaField;
            }
            set {
                this.italiaField = value;
                this.RaisePropertyChanged("italia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long partenze {
            get {
                return this.partenzeField;
            }
            set {
                this.partenzeField = value;
                this.RaisePropertyChanged("partenze");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string targa {
            get {
                return this.targaField;
            }
            set {
                this.targaField = value;
                this.RaisePropertyChanged("targa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/")]
    public partial class struttura : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private long struttura1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("struttura", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long struttura1 {
            get {
                return this.struttura1Field;
            }
            set {
                this.struttura1Field = value;
                this.RaisePropertyChanged("struttura1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(dettaglioMovimentiC59PO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(c59PO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/")]
    public abstract partial class commonPO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idObjField;
        
        private bool idObjFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long idObj {
            get {
                return this.idObjField;
            }
            set {
                this.idObjField = value;
                this.RaisePropertyChanged("idObj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idObjSpecified {
            get {
                return this.idObjFieldSpecified;
            }
            set {
                this.idObjFieldSpecified = value;
                this.RaisePropertyChanged("idObjSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/")]
    public partial class dettaglioMovimentiC59PO : commonPO {
        
        private long arriviField;
        
        private bool arriviFieldSpecified;
        
        private System.DateTime dataMovimentazioneField;
        
        private bool dataMovimentazioneFieldSpecified;
        
        private long idNazioneField;
        
        private bool idNazioneFieldSpecified;
        
        private long idProvinciaField;
        
        private bool idProvinciaFieldSpecified;
        
        private bool isItaliaField;
        
        private bool isItaliaFieldSpecified;
        
        private long numeroAlloggiField;
        
        private bool numeroAlloggiFieldSpecified;
        
        private long partenzeField;
        
        private bool partenzeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long arrivi {
            get {
                return this.arriviField;
            }
            set {
                this.arriviField = value;
                this.RaisePropertyChanged("arrivi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool arriviSpecified {
            get {
                return this.arriviFieldSpecified;
            }
            set {
                this.arriviFieldSpecified = value;
                this.RaisePropertyChanged("arriviSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime dataMovimentazione {
            get {
                return this.dataMovimentazioneField;
            }
            set {
                this.dataMovimentazioneField = value;
                this.RaisePropertyChanged("dataMovimentazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataMovimentazioneSpecified {
            get {
                return this.dataMovimentazioneFieldSpecified;
            }
            set {
                this.dataMovimentazioneFieldSpecified = value;
                this.RaisePropertyChanged("dataMovimentazioneSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long idNazione {
            get {
                return this.idNazioneField;
            }
            set {
                this.idNazioneField = value;
                this.RaisePropertyChanged("idNazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idNazioneSpecified {
            get {
                return this.idNazioneFieldSpecified;
            }
            set {
                this.idNazioneFieldSpecified = value;
                this.RaisePropertyChanged("idNazioneSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long idProvincia {
            get {
                return this.idProvinciaField;
            }
            set {
                this.idProvinciaField = value;
                this.RaisePropertyChanged("idProvincia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProvinciaSpecified {
            get {
                return this.idProvinciaFieldSpecified;
            }
            set {
                this.idProvinciaFieldSpecified = value;
                this.RaisePropertyChanged("idProvinciaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool isItalia {
            get {
                return this.isItaliaField;
            }
            set {
                this.isItaliaField = value;
                this.RaisePropertyChanged("isItalia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isItaliaSpecified {
            get {
                return this.isItaliaFieldSpecified;
            }
            set {
                this.isItaliaFieldSpecified = value;
                this.RaisePropertyChanged("isItaliaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long numeroAlloggi {
            get {
                return this.numeroAlloggiField;
            }
            set {
                this.numeroAlloggiField = value;
                this.RaisePropertyChanged("numeroAlloggi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroAlloggiSpecified {
            get {
                return this.numeroAlloggiFieldSpecified;
            }
            set {
                this.numeroAlloggiFieldSpecified = value;
                this.RaisePropertyChanged("numeroAlloggiSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long partenze {
            get {
                return this.partenzeField;
            }
            set {
                this.partenzeField = value;
                this.RaisePropertyChanged("partenze");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool partenzeSpecified {
            get {
                return this.partenzeFieldSpecified;
            }
            set {
                this.partenzeFieldSpecified = value;
                this.RaisePropertyChanged("partenzeSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/")]
    public partial class c59PO : commonPO {
        
        private System.DateTime dataMovimentazioneField;
        
        private bool dataMovimentazioneFieldSpecified;
        
        private bool isEsercizioApertoField;
        
        private bool isEsercizioApertoFieldSpecified;
        
        private bool isValidatoField;
        
        private bool isValidatoFieldSpecified;
        
        private dettaglioMovimentiC59PO[] listaDettaglioMovimentiField;
        
        private long totaleArriviField;
        
        private bool totaleArriviFieldSpecified;
        
        private long totalePartenzeField;
        
        private bool totalePartenzeFieldSpecified;
        
        private long totalePresentiField;
        
        private bool totalePresentiFieldSpecified;
        
        private long unitaAbitativeDisponibiliField;
        
        private bool unitaAbitativeDisponibiliFieldSpecified;
        
        private long unitaAbitativeOccupateField;
        
        private bool unitaAbitativeOccupateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime dataMovimentazione {
            get {
                return this.dataMovimentazioneField;
            }
            set {
                this.dataMovimentazioneField = value;
                this.RaisePropertyChanged("dataMovimentazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataMovimentazioneSpecified {
            get {
                return this.dataMovimentazioneFieldSpecified;
            }
            set {
                this.dataMovimentazioneFieldSpecified = value;
                this.RaisePropertyChanged("dataMovimentazioneSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool isEsercizioAperto {
            get {
                return this.isEsercizioApertoField;
            }
            set {
                this.isEsercizioApertoField = value;
                this.RaisePropertyChanged("isEsercizioAperto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isEsercizioApertoSpecified {
            get {
                return this.isEsercizioApertoFieldSpecified;
            }
            set {
                this.isEsercizioApertoFieldSpecified = value;
                this.RaisePropertyChanged("isEsercizioApertoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool isValidato {
            get {
                return this.isValidatoField;
            }
            set {
                this.isValidatoField = value;
                this.RaisePropertyChanged("isValidato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isValidatoSpecified {
            get {
                return this.isValidatoFieldSpecified;
            }
            set {
                this.isValidatoFieldSpecified = value;
                this.RaisePropertyChanged("isValidatoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaDettaglioMovimenti", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public dettaglioMovimentiC59PO[] listaDettaglioMovimenti {
            get {
                return this.listaDettaglioMovimentiField;
            }
            set {
                this.listaDettaglioMovimentiField = value;
                this.RaisePropertyChanged("listaDettaglioMovimenti");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long totaleArrivi {
            get {
                return this.totaleArriviField;
            }
            set {
                this.totaleArriviField = value;
                this.RaisePropertyChanged("totaleArrivi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totaleArriviSpecified {
            get {
                return this.totaleArriviFieldSpecified;
            }
            set {
                this.totaleArriviFieldSpecified = value;
                this.RaisePropertyChanged("totaleArriviSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long totalePartenze {
            get {
                return this.totalePartenzeField;
            }
            set {
                this.totalePartenzeField = value;
                this.RaisePropertyChanged("totalePartenze");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalePartenzeSpecified {
            get {
                return this.totalePartenzeFieldSpecified;
            }
            set {
                this.totalePartenzeFieldSpecified = value;
                this.RaisePropertyChanged("totalePartenzeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long totalePresenti {
            get {
                return this.totalePresentiField;
            }
            set {
                this.totalePresentiField = value;
                this.RaisePropertyChanged("totalePresenti");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalePresentiSpecified {
            get {
                return this.totalePresentiFieldSpecified;
            }
            set {
                this.totalePresentiFieldSpecified = value;
                this.RaisePropertyChanged("totalePresentiSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public long unitaAbitativeDisponibili {
            get {
                return this.unitaAbitativeDisponibiliField;
            }
            set {
                this.unitaAbitativeDisponibiliField = value;
                this.RaisePropertyChanged("unitaAbitativeDisponibili");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unitaAbitativeDisponibiliSpecified {
            get {
                return this.unitaAbitativeDisponibiliFieldSpecified;
            }
            set {
                this.unitaAbitativeDisponibiliFieldSpecified = value;
                this.RaisePropertyChanged("unitaAbitativeDisponibiliSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public long unitaAbitativeOccupate {
            get {
                return this.unitaAbitativeOccupateField;
            }
            set {
                this.unitaAbitativeOccupateField = value;
                this.RaisePropertyChanged("unitaAbitativeOccupate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unitaAbitativeOccupateSpecified {
            get {
                return this.unitaAbitativeOccupateFieldSpecified;
            }
            set {
                this.unitaAbitativeOccupateFieldSpecified = value;
                this.RaisePropertyChanged("unitaAbitativeOccupateSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/")]
    public partial class movimentiC59 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private c59PO[] elencoC59Field;
        
        private long strutturaField;
        
        private bool strutturaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("elencoC59", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public c59PO[] elencoC59 {
            get {
                return this.elencoC59Field;
            }
            set {
                this.elencoC59Field = value;
                this.RaisePropertyChanged("elencoC59");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long struttura {
            get {
                return this.strutturaField;
            }
            set {
                this.strutturaField = value;
                this.RaisePropertyChanged("struttura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool strutturaSpecified {
            get {
                return this.strutturaFieldSpecified;
            }
            set {
                this.strutturaFieldSpecified = value;
                this.RaisePropertyChanged("strutturaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="inviaC59Full", WrapperNamespace="http://movimentazione.manager.web.module.dtu.infotn.it/", IsWrapped=true)]
    public partial class inviaC59Full {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long struttura;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BookingCalendarApi.NETFramework.C59Service.c59WSPO c59;
        
        public inviaC59Full() {
        }
        
        public inviaC59Full(string username, string password, long struttura, BookingCalendarApi.NETFramework.C59Service.c59WSPO c59) {
            this.username = username;
            this.password = password;
            this.struttura = struttura;
            this.c59 = c59;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="inviaC59FullResponse", WrapperNamespace="http://movimentazione.manager.web.module.dtu.infotn.it/", IsWrapped=true)]
    public partial class inviaC59FullResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BookingCalendarApi.NETFramework.C59Service.c59WSPO[] @return;
        
        public inviaC59FullResponse() {
        }
        
        public inviaC59FullResponse(BookingCalendarApi.NETFramework.C59Service.c59WSPO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ultimoC59", WrapperNamespace="http://movimentazione.manager.web.module.dtu.infotn.it/", IsWrapped=true)]
    public partial class ultimoC59 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long struttura;
        
        public ultimoC59() {
        }
        
        public ultimoC59(string username, string password, long struttura) {
            this.username = username;
            this.password = password;
            this.struttura = struttura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ultimoC59Response", WrapperNamespace="http://movimentazione.manager.web.module.dtu.infotn.it/", IsWrapped=true)]
    public partial class ultimoC59Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BookingCalendarApi.NETFramework.C59Service.movimentiC59 @return;
        
        public ultimoC59Response() {
        }
        
        public ultimoC59Response(BookingCalendarApi.NETFramework.C59Service.movimentiC59 @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaStrutture", WrapperNamespace="http://movimentazione.manager.web.module.dtu.infotn.it/", IsWrapped=true)]
    public partial class listaStrutture {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public listaStrutture() {
        }
        
        public listaStrutture(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listaStruttureResponse", WrapperNamespace="http://movimentazione.manager.web.module.dtu.infotn.it/", IsWrapped=true)]
    public partial class listaStruttureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BookingCalendarApi.NETFramework.C59Service.struttura[] @return;
        
        public listaStruttureResponse() {
        }
        
        public listaStruttureResponse(BookingCalendarApi.NETFramework.C59Service.struttura[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="inviaC59", WrapperNamespace="http://movimentazione.manager.web.module.dtu.infotn.it/", IsWrapped=true)]
    public partial class inviaC59 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long struttura;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dataMovimentazione;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long unitaAbitativeOccupate;
        
        public inviaC59() {
        }
        
        public inviaC59(string username, string password, long struttura, System.DateTime dataMovimentazione, long unitaAbitativeOccupate) {
            this.username = username;
            this.password = password;
            this.struttura = struttura;
            this.dataMovimentazione = dataMovimentazione;
            this.unitaAbitativeOccupate = unitaAbitativeOccupate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="inviaC59Response", WrapperNamespace="http://movimentazione.manager.web.module.dtu.infotn.it/", IsWrapped=true)]
    public partial class inviaC59Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://movimentazione.manager.web.module.dtu.infotn.it/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BookingCalendarApi.NETFramework.C59Service.movimentiC59 @return;
        
        public inviaC59Response() {
        }
        
        public inviaC59Response(BookingCalendarApi.NETFramework.C59Service.movimentiC59 @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EC59ServiceEndpointChannel : BookingCalendarApi.NETFramework.C59Service.EC59ServiceEndpoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EC59ServiceEndpointClient : System.ServiceModel.ClientBase<BookingCalendarApi.NETFramework.C59Service.EC59ServiceEndpoint>, BookingCalendarApi.NETFramework.C59Service.EC59ServiceEndpoint {
        
        public EC59ServiceEndpointClient() {
        }
        
        public EC59ServiceEndpointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EC59ServiceEndpointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EC59ServiceEndpointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EC59ServiceEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookingCalendarApi.NETFramework.C59Service.inviaC59FullResponse BookingCalendarApi.NETFramework.C59Service.EC59ServiceEndpoint.inviaC59Full(BookingCalendarApi.NETFramework.C59Service.inviaC59Full request) {
            return base.Channel.inviaC59Full(request);
        }
        
        public BookingCalendarApi.NETFramework.C59Service.c59WSPO[] inviaC59Full(string username, string password, long struttura, BookingCalendarApi.NETFramework.C59Service.c59WSPO c59) {
            BookingCalendarApi.NETFramework.C59Service.inviaC59Full inValue = new BookingCalendarApi.NETFramework.C59Service.inviaC59Full();
            inValue.username = username;
            inValue.password = password;
            inValue.struttura = struttura;
            inValue.c59 = c59;
            BookingCalendarApi.NETFramework.C59Service.inviaC59FullResponse retVal = ((BookingCalendarApi.NETFramework.C59Service.EC59ServiceEndpoint)(this)).inviaC59Full(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookingCalendarApi.NETFramework.C59Service.inviaC59FullResponse> BookingCalendarApi.NETFramework.C59Service.EC59ServiceEndpoint.inviaC59FullAsync(BookingCalendarApi.NETFramework.C59Service.inviaC59Full request) {
            return base.Channel.inviaC59FullAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookingCalendarApi.NETFramework.C59Service.inviaC59FullResponse> inviaC59FullAsync(string username, string password, long struttura, BookingCalendarApi.NETFramework.C59Service.c59WSPO c59) {
            BookingCalendarApi.NETFramework.C59Service.inviaC59Full inValue = new BookingCalendarApi.NETFramework.C59Service.inviaC59Full();
            inValue.username = username;
            inValue.password = password;
            inValue.struttura = struttura;
            inValue.c59 = c59;
            return ((BookingCalendarApi.NETFramework.C59Service.EC59ServiceEndpoint)(this)).inviaC59FullAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookingCalendarApi.NETFramework.C59Service.ultimoC59Response BookingCalendarApi.NETFramework.C59Service.EC59ServiceEndpoint.ultimoC59(BookingCalendarApi.NETFramework.C59Service.ultimoC59 request) {
            return base.Channel.ultimoC59(request);
        }
        
        public BookingCalendarApi.NETFramework.C59Service.movimentiC59 ultimoC59(string username, string password, long struttura) {
            BookingCalendarApi.NETFramework.C59Service.ultimoC59 inValue = new BookingCalendarApi.NETFramework.C59Service.ultimoC59();
            inValue.username = username;
            inValue.password = password;
            inValue.struttura = struttura;
            BookingCalendarApi.NETFramework.C59Service.ultimoC59Response retVal = ((BookingCalendarApi.NETFramework.C59Service.EC59ServiceEndpoint)(this)).ultimoC59(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookingCalendarApi.NETFramework.C59Service.ultimoC59Response> BookingCalendarApi.NETFramework.C59Service.EC59ServiceEndpoint.ultimoC59Async(BookingCalendarApi.NETFramework.C59Service.ultimoC59 request) {
            return base.Channel.ultimoC59Async(request);
        }
        
        public System.Threading.Tasks.Task<BookingCalendarApi.NETFramework.C59Service.ultimoC59Response> ultimoC59Async(string username, string password, long struttura) {
            BookingCalendarApi.NETFramework.C59Service.ultimoC59 inValue = new BookingCalendarApi.NETFramework.C59Service.ultimoC59();
            inValue.username = username;
            inValue.password = password;
            inValue.struttura = struttura;
            return ((BookingCalendarApi.NETFramework.C59Service.EC59ServiceEndpoint)(this)).ultimoC59Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookingCalendarApi.NETFramework.C59Service.listaStruttureResponse BookingCalendarApi.NETFramework.C59Service.EC59ServiceEndpoint.listaStrutture(BookingCalendarApi.NETFramework.C59Service.listaStrutture request) {
            return base.Channel.listaStrutture(request);
        }
        
        public BookingCalendarApi.NETFramework.C59Service.struttura[] listaStrutture(string username, string password) {
            BookingCalendarApi.NETFramework.C59Service.listaStrutture inValue = new BookingCalendarApi.NETFramework.C59Service.listaStrutture();
            inValue.username = username;
            inValue.password = password;
            BookingCalendarApi.NETFramework.C59Service.listaStruttureResponse retVal = ((BookingCalendarApi.NETFramework.C59Service.EC59ServiceEndpoint)(this)).listaStrutture(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookingCalendarApi.NETFramework.C59Service.listaStruttureResponse> BookingCalendarApi.NETFramework.C59Service.EC59ServiceEndpoint.listaStruttureAsync(BookingCalendarApi.NETFramework.C59Service.listaStrutture request) {
            return base.Channel.listaStruttureAsync(request);
        }
        
        public System.Threading.Tasks.Task<BookingCalendarApi.NETFramework.C59Service.listaStruttureResponse> listaStruttureAsync(string username, string password) {
            BookingCalendarApi.NETFramework.C59Service.listaStrutture inValue = new BookingCalendarApi.NETFramework.C59Service.listaStrutture();
            inValue.username = username;
            inValue.password = password;
            return ((BookingCalendarApi.NETFramework.C59Service.EC59ServiceEndpoint)(this)).listaStruttureAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BookingCalendarApi.NETFramework.C59Service.inviaC59Response BookingCalendarApi.NETFramework.C59Service.EC59ServiceEndpoint.inviaC59(BookingCalendarApi.NETFramework.C59Service.inviaC59 request) {
            return base.Channel.inviaC59(request);
        }
        
        public BookingCalendarApi.NETFramework.C59Service.movimentiC59 inviaC59(string username, string password, long struttura, System.DateTime dataMovimentazione, long unitaAbitativeOccupate) {
            BookingCalendarApi.NETFramework.C59Service.inviaC59 inValue = new BookingCalendarApi.NETFramework.C59Service.inviaC59();
            inValue.username = username;
            inValue.password = password;
            inValue.struttura = struttura;
            inValue.dataMovimentazione = dataMovimentazione;
            inValue.unitaAbitativeOccupate = unitaAbitativeOccupate;
            BookingCalendarApi.NETFramework.C59Service.inviaC59Response retVal = ((BookingCalendarApi.NETFramework.C59Service.EC59ServiceEndpoint)(this)).inviaC59(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BookingCalendarApi.NETFramework.C59Service.inviaC59Response> BookingCalendarApi.NETFramework.C59Service.EC59ServiceEndpoint.inviaC59Async(BookingCalendarApi.NETFramework.C59Service.inviaC59 request) {
            return base.Channel.inviaC59Async(request);
        }
        
        public System.Threading.Tasks.Task<BookingCalendarApi.NETFramework.C59Service.inviaC59Response> inviaC59Async(string username, string password, long struttura, System.DateTime dataMovimentazione, long unitaAbitativeOccupate) {
            BookingCalendarApi.NETFramework.C59Service.inviaC59 inValue = new BookingCalendarApi.NETFramework.C59Service.inviaC59();
            inValue.username = username;
            inValue.password = password;
            inValue.struttura = struttura;
            inValue.dataMovimentazione = dataMovimentazione;
            inValue.unitaAbitativeOccupate = unitaAbitativeOccupate;
            return ((BookingCalendarApi.NETFramework.C59Service.EC59ServiceEndpoint)(this)).inviaC59Async(inValue);
        }
    }
}
